// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

// func InitMission(n1 PlayerParam, n2 MonsterParam) (Mission, error) {
func InitMission() (Mission, error) {
	mission := Mission{}
	return mission, nil
}

func InitEndingA(n1 PlayerParam, n2 MonsterParam) (EndingA, error) {
	player, err := NewPlayer(n1)
	if err != nil {
		return EndingA{}, err
	}
	monster := NewMonster(n2)
	endingA := EndingA{
		Player:  player,
		Monster: monster,
	}
	return endingA, nil
}

func InitEndingB(n1 PlayerParam, n2 MonsterParam) (EndingB, error) {
	player, err := NewPlayer(n1)
	if err != nil {
		return EndingB{}, err
	}
	monster := NewMonster(n2)
	endingB := EndingB{
		Player:  player,
		Monster: monster,
	}
	return endingB, nil
}

// wire.go:

var monsterPlayerSet = wire.NewSet(NewMonster, NewPlayer)

var endingASet = wire.NewSet(monsterPlayerSet, wire.Struct(new(EndingA), "*"))

var endingBSet = wire.NewSet(wire.Struct(new(EndingB), "*"), monsterPlayerSet)
